[build]
  functions = "netlify/functions"
  publish = "dist"

[functions]
  node_bundler = "esbuild"

[dev]
  framework = "vite"
  targetPort = 3000
  port = 8888

[build.environment]
  NODE_VERSION = "20"

# --- Netlify Blobs ストア定義 ---
[[blobs]]
  name = "quizzes"

# 診断用ストア（testConnection.ts で利用）
[[blobs]]
  name = "connection-test"
